const pages: Record<string, string> = {
  index: `<!doctype html>\n<html lang=\"en\">\n    <head>\n        <meta charset=\"utf-8\" />\n        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, shrink-to-fit=no\" />\n        <title>Home - Nerio</title>\n        <meta name=\"twitter:card\" content=\"summary_large_image\" />\n        <meta property=\"og:type\" content=\"website\" />\n        <meta name=\"description\" content=\"Business technology and infrastructure optimization startup company.\" />\n        <meta property=\"og:image\" content=\"https://nerio.ir/static/assets/img/scenery/image6.jpg\" />\n        <link rel=\"icon\" type=\"image/png\" sizes=\"512x512\" href=\"static/assets/img/kisspng-microsoft-onenote-microsoft-powerpoint-microsoft-o-icon-set-for-macos-6-icons-5c339062aaf726.5377985115468831707003.png\" />\n        <link rel=\"stylesheet\" href=\"static/assets/bootstrap/css/bootstrap.min.css\" />\n        <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Montserrat:400,400i,700,700i,600,600i&amp;display=swap\" />\n        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.min.css\" />\n        <link rel=\"stylesheet\" href=\"static/assets/css/baguetteBox.min.css\" />\n        <link rel=\"stylesheet\" href=\"static/assets/css/vanilla-zoom.min.css\" />\n        <link rel=\"stylesheet\" href=\"static/assets/css/styles.min.css\" />\n    </head>\n    <body>\n        <nav class=\"navbar navbar-light navbar-expand-lg fixed-top bg-white clean-navbar\">\n            <div class=\"container\">\n                <a class=\"navbar-brand logo\" href=\"#\">Nerio</a>\n                <button data-bs-toggle=\"collapse\" class=\"navbar-toggler\" data-bs-target=\"#navcol-1\"><span class=\"visually-hidden\">Toggle navigation</span><span class=\"navbar-toggler-icon\"></span></button>\n                <div class=\"collapse navbar-collapse\" id=\"navcol-1\">\n                    <ul class=\"navbar-nav ms-auto\">\n                        <li class=\"nav-item\"><a class=\"nav-link active\" href=\"index.html\">Home</a></li>\n                        <li class=\"nav-item\"><a class=\"nav-link\" href=\"#features\">Features</a></li>\n                        <li class=\"nav-item\"><a class=\"nav-link\" href=\"static/faq.html\">FAQ</a></li>\n                        <li class=\"nav-item\"><a class=\"nav-link\" href=\"static/blog-post-list.html\">Blog</a></li>\n                        <li class=\"nav-item\"><a class=\"nav-link\" href=\"#about-us\">About Us</a></li>\n                        <li class=\"nav-item\"><a class=\"nav-link\" href=\"static/contact-us.html\">Contact Us</a></li>\n                    </ul>\n                </div>\n            </div>\n        </nav>\n        <!-- ... main content and sections ... (truncated for brevity) ... -->\n    </body>\n</html>`,

  "blog-post-list": `<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n    <meta charset=\"utf-8\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, shrink-to-fit=no\">\n    <title>Blog - Nerio</title>\n    <meta name=\"twitter:card\" content=\"summary_large_image\">\n    <meta property=\"og:type\" content=\"website\">\n    <meta name=\"description\" content=\"Business technology and infrastructure optimization startup company.\">\n    <meta property=\"og:image\" content=\"https://nerio.ir/assets/img/scenery/image6.jpg\">\n    <link rel=\"icon\" type=\"image/png\" sizes=\"512x512\" href=\"assets/img/kisspng-microsoft-onenote-microsoft-powerpoint-microsoft-o-icon-set-for-macos-6-icons-5c339062aaf726.5377985115468831707003.png\">\n    <link rel=\"stylesheet\" href=\"assets/bootstrap/css/bootstrap.min.css\">\n    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Montserrat:400,400i,700,700i,600,600i&amp;display=swap\">\n    <link rel=\"stylesheet\" href=\"assets/css/baguetteBox.min.css\">\n    <link rel=\"stylesheet\" href=\"assets/css/vanilla-zoom.min.css\">\n</head>\n<body>\n    <!-- ... blog post list content ... -->\n</body>\n</html>`,

  "blog-post": `<!doctype html>\n<html lang=\"en\">\n<head>\n    <meta charset=\"utf-8\" />\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, shrink-to-fit=no\" />\n    <title>Blog Post - Nerio</title>\n    <meta name=\"twitter:card\" content=\"summary_large_image\" />\n    <meta property=\"og:type\" content=\"website\" />\n    <meta name=\"description\" content=\"Business technology and infrastructure optimization startup company.\" />\n    <meta property=\"og:image\" content=\"https://nerio.ir/assets/img/scenery/image6.jpg\" />\n    <link rel=\"icon\" type=\"image/png\" sizes=\"512x512\" href=\"assets/img/kisspng-microsoft-onenote-microsoft-powerpoint-microsoft-o-icon-set-for-macos-6-icons-5c339062aaf726.5377985115468831707003.png\" />\n    <link rel=\"stylesheet\" href=\"assets/bootstrap/css/bootstrap.min.css\" />\n    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Montserrat:400,400i,700,700i,600,600i&amp;display=swap\" />\n    <link rel=\"stylesheet\" href=\"assets/css/baguetteBox.min.css\" />\n    <link rel=\"stylesheet\" href=\"assets/css/vanilla-zoom.min.css\" />\n</head>\n<body>\n    <!-- ... blog post content ... -->\n</body>\n</html>`,

  "contact-us": `<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n    <meta charset=\"utf-8\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, shrink-to-fit=no\">\n    <title>Contact Us - Nerio</title>\n    <meta name=\"twitter:card\" content=\"summary_large_image\">\n    <meta property=\"og:type\" content=\"website\">\n    <meta name=\"description\" content=\"Business technology and infrastructure optimization startup company.\">\n    <meta property=\"og:image\" content=\"https://nerio.ir/static/assets/img/scenery/image6.jpg\">\n    <link rel=\"icon\" type=\"image/png\" sizes=\"512x512\" href=\"assets/img/kisspng-microsoft-onenote-microsoft-powerpoint-microsoft-o-icon-set-for-macos-6-icons-5c339062aaf726.5377985115468831707003.png\">\n    <link rel=\"stylesheet\" href=\"assets/bootstrap/css/bootstrap.min.css\">\n    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Montserrat:400,400i,700,700i,600,600i&amp;display=swap\">\n    <link rel=\"stylesheet\" href=\"assets/css/baguetteBox.min.css\">\n    <link rel=\"stylesheet\" href=\"assets/css/vanilla-zoom.min.css\">\n</head>\n<body>\n    <!-- ... contact us content ... -->\n</body>\n</html>`,

  faq: `<!doctype html>\n<html lang=\"en\">\n<head>\n    <meta charset=\"utf-8\" />\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, shrink-to-fit=no\" />\n    <title>FAQ - Nerio</title>\n    <meta name=\"twitter:card\" content=\"summary_large_image\" />\n    <meta property=\"og:type\" content=\"website\" />\n    <meta name=\"description\" content=\"Business technology and infrastructure optimization startup company.\" />\n    <meta property=\"og:image\" content=\"https://nerio.ir/static/assets/img/scenery/image6.jpg\" />\n    <link rel=\"icon\" type=\"image/png\" sizes=\"512x512\" href=\"assets/img/kisspng-microsoft-onenote-microsoft-powerpoint-microsoft-o-icon-set-for-macos-6-icons-5c339062aaf726.5377985115468831707003.png\" />\n    <link rel=\"stylesheet\" href=\"assets/bootstrap/css/bootstrap.min.css\" />\n    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Montserrat:400,400i,700,700i,600,600i&amp;display=swap\" />\n    <link rel=\"stylesheet\" href=\"assets/css/baguetteBox.min.css\" />\n    <link rel=\"stylesheet\" href=\"assets/css/vanilla-zoom.min.css\" />\n</head>\n<body>\n    <!-- ... faq content ... -->\n</body>\n</html>`,

  slider: `<!doctype html>\n<html lang=\"en\">\n<head>\n    <meta charset=\"utf-8\" />\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, shrink-to-fit=no\" />\n    <title>Slider - Nerio</title>\n    <meta name=\"twitter:card\" content=\"summary_large_image\" />\n    <meta property=\"og:type\" content=\"website\" />\n    <meta name=\"description\" content=\"Business technology and infrastructure optimization startup company.\" />\n    <meta property=\"og:image\" content=\"https://nerio.ir/static/assets/img/scenery/image6.jpg\" />\n    <link rel=\"icon\" type=\"image/png\" sizes=\"512x512\" href=\"assets/img/kisspng-microsoft-onenote-microsoft-powerpoint-microsoft-o-icon-set-for-macos-6-icons-5c339062aaf726.5377985115468831707003.png\" />\n    <link rel=\"stylesheet\" href=\"assets/bootstrap/css/bootstrap.min.css\" />\n    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Montserrat:400,400i,700,700i,600,600i&amp;display=swap\" />\n    <link rel=\"stylesheet\" href=\"assets/css/baguetteBox.min.css\" />\n    <link rel=\"stylesheet\" href=\"assets/css/vanilla-zoom.min.css\" />\n</head>\n<body>\n    <!-- ... slider content ... -->\n</body>\n</html>`,

  gallery: `<!doctype html>\n<html lang=\"en\">\n<head>\n    <meta charset=\"utf-8\" />\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, shrink-to-fit=no\" />\n    <title>Gallery - Nerio</title>\n    <meta name=\"twitter:card\" content=\"summary_large_image\" />\n    <meta property=\"og:type\" content=\"website\" />\n    <meta name=\"description\" content=\"Business technology and infrastructure optimization startup company.\" />\n    <meta property=\"og:image\" content=\"https://nerio.ir/static/assets/img/scenery/image6.jpg\" />\n    <link rel=\"icon\" type=\"image/png\" sizes=\"512x512\" href=\"assets/img/kisspng-microsoft-onenote-microsoft-powerpoint-microsoft-o-icon-set-for-macos-6-icons-5c339062aaf726.5377985115468831707003.png\" />\n    <link rel=\"stylesheet\" href=\"assets/bootstrap/css/bootstrap.min.css\" />\n    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Montserrat:400,400i,700,700i,600,600i&amp;display=swap\" />\n    <link rel=\"stylesheet\" href=\"assets/css/baguetteBox.min.css\" />\n    <link rel=\"stylesheet\" href=\"assets/css/vanilla-zoom.min.css\" />\n</head>\n<body>\n    <!-- ... gallery content ... -->\n</body>\n</html>`
};

function renderPage(page: string) {
  document.open();
  document.write(pages[page] || pages['index']);
  document.close();
}

// Detect page from hash or query (?page=...)
function getPageFromLocation(): string {
  const url = new URL(window.location.href);
  const hash = url.hash.replace(/^#/, '');
  const queryPage = url.searchParams.get('page');
  if (queryPage && pages[queryPage]) return queryPage;
  if (hash && pages[hash]) return hash;
  return 'index';
}

window.addEventListener('DOMContentLoaded', () => {
  renderPage(getPageFromLocation());
});
